import type { Metadata } from "next";
import { Sora, Montagu_Slab, Noto_Sans_Mono, Lexend } from "next/font/google";
import "@/app/globals.css";
import styles from "./layout.module.css";
import Navigation from "@/app/components/navigation/navigation";
import Footer from "@/app/components/footer/footer";
import Line from "../components/metro-line/line/line";

const sora = Sora({
  variable: "--font-sora",
  weight: ["600"],
  subsets: ["latin"],
});

const montaguSlab = Montagu_Slab({
  variable: "--font-montagu-slab",
  weight: ["600"],
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const notoSansMono = Noto_Sans_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-noto-sans-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body
      className={`${styles.body}
        ${sora.variable} ${montaguSlab.variable} ${lexend.variable} ${notoSansMono.variable}
        antialiased`}
      >
        <div className={styles.navigationContainer}>
          <Navigation />
        </div>

        
        <div
        className={styles.lineWrapper}
        >
          <Line />
        </div>

        {children}
        <Footer />
        
      </body>
    </html>
  );
}
