import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import styles from "./layout.module.css";
import Navigation from "@/app/components/navigation/navigation";
import Footer from "@/app/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${styles.body} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.navigationContainer}>
          <Navigation />
        </div>

        <div className={styles.scrollableContainer}>
          {children}
          <Footer />
        </div>
        
      </body>
    </html>
  );
}
